@{
    # Module manifest for PSMouseJiggler
    # Generated by: Steven Wight (PowerShell Young Team)
    # Generated on: $(Get-Date)

    # Script module or binary module file associated with this manifest.
    RootModule             = 'PSMouseJiggler.psm1'

    # Version number of this module.
    ModuleVersion          = '1.0.4'

    # Supported PSEditions
    CompatiblePSEditions   = @('Desktop', 'Core')

    # ID used to uniquely identify this module
    GUID                   = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'

    # Author of this module
    Author                 = 'Steven Wight (PowerShell Young Team)'

    # Company or vendor of this module
    CompanyName            = 'Unknown'

    # Copyright statement for this module
    Copyright              = '(c) Steven Wight (PowerShell Young Team). All rights reserved.'

    # Description of the functionality provided by this module
    Description            = 'A PowerShell module to simulate mouse movements and prevent system idle. Includes GUI interface, configurable movement patterns, and scheduled task support.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion      = '5.1'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    DotNetFrameworkVersion = '4.7.2'

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies     = @('System.Windows.Forms', 'System.Drawing')

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport      = @(
        'Start-PSMouseJiggler',
        'Stop-PSMouseJiggler',
        'Get-NewMousePosition',
        'Show-PSMouseJigglerGUI',
        'Get-Configuration',
        'Save-Configuration',
        'Update-Configuration',
        'Reset-Configuration',
        'Get-RandomMovementPattern',
        'Move-Mouse',
        'Start-MovementPattern',
        'Stop-MovementPattern',
        'Get-PSMJScheduledTasks',       # Updated name
        'New-PSMJScheduledTask',        # Updated name
        'Remove-PSMJScheduledTask',     # Updated name
        'Start-PSMJScheduledTask',      # Updated name
        'Stop-PSMJScheduledTask',       # Updated name
        'Prevent-SystemIdle',
        'Send-KeyboardInput',
        'Send-MouseInput',
        'Start-KeepAwake'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport        = @()

    # Variables to export from this module
    VariablesToExport      = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport        = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData            = @{
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags                     = @('Mouse', 'Jiggler', 'Automation', 'Anti-Idle', 'GUI', 'Windows')

            # A URL to the license for this module.
            LicenseUri               = 'https://github.com/PowerShellYoungTeam/PSMouseJiggler/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri               = 'https://github.com/PowerShellYoungTeam/PSMouseJiggler'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes             = @'
            Version 1.0.4
            Add Incognito Mode feature for discrete operation in GUI and console by @PowerShellYoungTeam in #13
                
            
                Version 1.0.3
                - Renamed scheduled task functions to prevent conflicts with other modules:
                    - Get-ScheduledTasks → Get-PSMJScheduledTasks
                    - New-ScheduledTask → New-PSMJScheduledTask
                    - Remove-ScheduledTask → Remove-PSMJScheduledTask
                    - Start-ScheduledTask → Start-PSMJScheduledTask
                    - Stop-ScheduledTask → Stop-PSMJScheduledTask
                - Fixed PSScriptAnalyzer warning
                - Improved module compatibility with other PowerShell modules

                Version 1.0.2
                - Added advanced keep-awake methods: combines mouse, keyboard, and system API techniques for reliable anti-idle functionality
                - Introduced hardware-level input simulation for broader compatibility with strict power management
                - New API functions: Prevent-SystemIdle, Send-KeyboardInput, Send-MouseInput, Start-KeepAwake for custom automation and integration
                - Updated GUI layout: supports advanced keep-awake options and method selection
                - Enhanced configuration management: improved loading, saving, and updating of user preferences
                - Improved scheduled task support for automated jiggling
                - Fixed variable naming to avoid PowerShell built-in conflicts
                - Minor bug fixes and usability improvements
                - Ready for PowerShell Gallery distribution
'@

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()
        }
    }

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
}
