@{
    # Module manifest for PSMouseJiggler
    # Generated by: Steven Wight (PowerShell Young Team)
    # Generated on: $(Get-Date)

    # Script module or binary module file associated with this manifest.
    RootModule           = 'PSMouseJiggler.psm1'

    # Version number of this module.
    ModuleVersion        = '2.0.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Desktop', 'Core')

    # ID used to uniquely identify this module
    GUID                 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'

    # Author of this module
    Author               = 'Steven Wight (PowerShell Young Team)'

    # Company or vendor of this module
    CompanyName          = 'Unknown'

    # Copyright statement for this module
    Copyright            = '(c) Steven Wight (PowerShell Young Team). All rights reserved.'

    # Description of the functionality provided by this module
    Description          = 'A cross-platform PowerShell module to simulate mouse movements and prevent system idle on Windows, Linux, and macOS. Includes GUI (Windows) and TUI (all platforms) interfaces, configurable movement patterns, and scheduled task support.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = '5.1'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = '4.7.2'  # Disabled for cross-platform support

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies     = @('System.Windows.Forms', 'System.Drawing')  # Loaded conditionally for Windows

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport    = @(
        # Core Functions
        'Start-PSMouseJiggler',
        'Stop-PSMouseJiggler',
        'Get-NewMousePosition',
        'Move-Mouse',
        'Start-MovementPattern',
        'Stop-MovementPattern',
        'Start-KeepAwake',

        # GUI/TUI Functions
        'Show-PSMouseJigglerGUI',
        'Show-PSMouseJigglerTUI',

        # Configuration Functions
        'Get-Configuration',
        'Save-Configuration',
        'Update-Configuration',
        'Reset-Configuration',
        'Get-RandomMovementPattern',

        # Scheduled Task Functions
        'Get-PSMJScheduledTasks',
        'New-PSMJScheduledTask',
        'Remove-PSMJScheduledTask',
        'Start-PSMJScheduledTask',
        'Stop-PSMJScheduledTask',

        # Keep-Awake Methods (Windows-specific)
        'Prevent-SystemIdle',
        'Send-KeyboardInput',
        'Send-MouseInput',

        # Platform Detection Helpers (v2.0.0)
        'Get-OperatingSystemPlatform',
        'Test-PlatformCapability',
        'Show-DependencyInstallInstructions'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport      = @()

    # Variables to export from this module
    VariablesToExport    = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport      = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData          = @{
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags                     = @('Mouse', 'Jiggler', 'Automation', 'Anti-Idle', 'GUI', 'TUI', 'Windows', 'Linux', 'macOS', 'Cross-Platform', 'Terminal')

            # A URL to the license for this module.
            LicenseUri               = 'https://github.com/PowerShellYoungTeam/PSMouseJiggler/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri               = 'https://github.com/PowerShellYoungTeam/PSMouseJiggler'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes             = @'
                Version 2.0.0 (November 2025) - MAJOR RELEASE: Cross-Platform Support
                ⚠️ BREAKING CHANGES:
                - Module now requires PowerShell 7+ for Linux and macOS (Windows PowerShell 5.1 still supported on Windows)
                - Windows Forms assemblies no longer loaded by default on non-Windows platforms
                - Some features are platform-specific (see documentation)

                ✨ NEW FEATURES:
                - 🌍 Cross-platform support: Works on Windows, Linux, and macOS
                - 🖥️ Linux support with xdotool/ydotool for mouse/keyboard simulation
                - 🍎 macOS support with cliclick for mouse/keyboard simulation
                - 🔋 Platform-specific idle prevention:
                  - Windows: SetThreadExecutionState API (existing)
                  - Linux: systemd-inhibit integration
                  - macOS: caffeinate wrapper
                - 📟 Terminal UI (TUI) interface available on all platforms (requires Microsoft.PowerShell.ConsoleGuiTools module)
                - 🎯 Platform detection with automatic feature adaptation
                - 🛠️ Automated dependency installer script (Install-PSMouseJigglerDependencies.ps1)
                - 📋 Platform-specific scheduled task support:
                  - Windows: Task Scheduler (existing)
                  - Linux: systemd timers with cron fallback
                  - macOS: launchd integration

                🔄 CHANGES:
                - Core functions refactored with platform abstraction layer
                - Windows Forms GUI remains Windows-only (fallback to TUI on other platforms)
                - External tool detection with helpful installation guidance
                - Graceful degradation when optional tools unavailable

                📚 DOCUMENTATION:
                - New PLATFORM_SUPPORT.md with detailed platform guides
                - New MANUAL_TESTING.md for platform-specific testing procedures
                - Updated all documentation with cross-platform examples
                - Migration guide for users upgrading from v1.x

                🔧 MAINTENANCE:
                - v1.1.0 branch maintained for Windows-only users
                - Multi-OS CI/CD testing (Windows, Linux, macOS)
                - Platform-specific test suites with Pester tags

                For users who prefer Windows-only version, install v1.1.0:
                Install-Module PSMouseJiggler -RequiredVersion 1.1.0

                Version 1.1.0 (October 2025)
                - Added modern tabbed GUI interface with three main tabs:
                    - Basic Mode: Simple mouse jiggling controls
                    - Advanced Mode: Multi-method keep-awake configuration
                    - Quick Launch: Five pre-configured profiles for common scenarios
                - Implemented Quick Launch profiles:
                    - [Mouse] Basic Discrete: Random movements with incognito mode
                    - [Lock] Maximum Security: Hardware + System API for strict policies
                    - [Key] Keyboard Only: Non-visual keep-awake method
                    - [API] System API Only: Minimal resource usage
                    - [MAX] All Methods: Maximum reliability
                - Added advanced keep-awake methods:
                    - Hardware-level mouse input using SendInput API
                    - Keyboard input simulation (F15 key presses)
                    - Direct Windows power management (SetThreadExecutionState API)
                - Created Start-KeepAwake function for multi-method keep-awake
                - Added -Incognito parameter to Start-PSMouseJiggler and Start-KeepAwake
                - Implemented Prevent-SystemIdle, Send-KeyboardInput, and Send-MouseInput functions
                - Enhanced GUI with incognito mode support (minimizes window, clears console)
                - Fixed emoji encoding issues in GUI (replaced with text labels)
                - Improved GUI state management for reopening after console start
                - Renamed scheduled task functions with PSMJ prefix (already in v1.0.3)
                - Comprehensive documentation updates across all README and USAGE files
                - Updated Get-Help comments with new parameters and examples
                - Requires .NET Framework 4.7.2+ for P/Invoke features

                Version 1.0.4
                - Add Incognito Mode feature for discrete operation in GUI and console by @PowerShellYoungTeam in #13

                Version 1.0.3
                - Renamed scheduled task functions to prevent conflicts with other modules:
                    - Get-ScheduledTasks → Get-PSMJScheduledTasks
                    - New-ScheduledTask → New-PSMJScheduledTask
                    - Remove-ScheduledTask → Remove-PSMJScheduledTask
                    - Start-ScheduledTask → Start-PSMJScheduledTask
                    - Stop-ScheduledTask → Stop-PSMJScheduledTask
                - Fixed PSScriptAnalyzer warning
                - Improved module compatibility with other PowerShell modules

                Version 1.0.2
                - Added advanced keep-awake methods: combines mouse, keyboard, and system API techniques for reliable anti-idle functionality
                - Introduced hardware-level input simulation for broader compatibility with strict power management
                - New API functions: Prevent-SystemIdle, Send-KeyboardInput, Send-MouseInput, Start-KeepAwake for custom automation and integration
                - Updated GUI layout: supports advanced keep-awake options and method selection
                - Enhanced configuration management: improved loading, saving, and updating of user preferences
                - Improved scheduled task support for automated jiggling
                - Fixed variable naming to avoid PowerShell built-in conflicts
                - Minor bug fixes and usability improvements
                - Ready for PowerShell Gallery distribution
'@

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()
        }
    }

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
}
