name: Publish Module

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:
    name: Publish to PowerShell Gallery
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        shell: pwsh
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck -MinimumVersion 5.0.0
          Install-Module -Name PSScriptAnalyzer -Force

      - name: Run tests
        shell: pwsh
        run: |
          $config = New-PesterConfiguration
          $config.Run.Path = ".\tests"
          $config.Run.PassThru = $true
          $results = Invoke-Pester -Configuration $config
          if ($results.FailedCount -gt 0) {
            throw "Pester tests failed"
          }

      - name: Validate Module Manifest
        shell: pwsh
        run: |
          $manifest = Test-ModuleManifest -Path .\src\PSMouseJiggler\PSMouseJiggler.psd1 -ErrorAction Stop
          $manifest | Format-List

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          $results = Invoke-ScriptAnalyzer -Path .\src -Recurse -Severity Error
          $results | Format-Table
          if ($results) { throw "PSScriptAnalyzer found $($results.Count) errors" }

      - name: Publish to PowerShell Gallery
        shell: pwsh
        env:
          PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
        run: |
          $modulePath = Join-Path $PWD "src\PSMouseJiggler"
          Publish-Module -Path $modulePath -NuGetApiKey $env:PSGALLERY_API_KEY -Verbose