name: Release

on:
  release:
    types: [published]

jobs:
  test-and-package:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Pester
        shell: pwsh
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck

      - name: Run tests
        shell: pwsh
        run: |
          Invoke-Pester -Script tests/PSMouseJiggler.Module.Tests.ps1

      - name: Package PSMouseJiggler
        shell: pwsh
        run: |
          # Create module package
          $version = "1.0.0"  # You can read this from the manifest if needed
          $outputPath = "PSMouseJiggler-$version.zip"
          Compress-Archive -Path PSMouseJiggler\* -DestinationPath $outputPath

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./PSMouseJiggler-1.0.0.zip
          asset_name: PSMouseJiggler-1.0.0.zip
          asset_content_type: application/zip